#!/bin/bash
echo ""
echo "################## WECOME TO CONFIG UTILITY, PLEASE ANSWER SOME QUESTIONS (OR DEFAULT OUT) #######"
echo ""
echo "Please enter a base directory for installation (default: /home/librenms)"
read BaseDIR
if [ -z "$BaseDIR" ]
then
	BaseDIR="/home/librenms"
fi
SQLUser="librenms"
echo "Please enter CPE Username (default: cisco)"
read CPEUser
if [ -z "$CPEUser" ]
then
	CPEUser="cisco"
fi
echo "Please enter CPE Password (default: generated)"
read CPEPass
if [ -z "$CPEPass" ]
then
	CPEPass=`tr -cd '[:alnum:]' < /dev/urandom | fold -w8 | head -n1`
fi
echo "Please enter the Hostname of the machine (default: librenms)"
read Hostname
if [ -z "$Hostname" ]
then
	Hostname="librenms"
fi
echo "Please enter Domain name of the machine (default: local)"
echo ""
echo "   Note: DNS name of the machine should be Hostname.Domain (default: librenms.local)"
echo "     ex: monitor.megacorp.ex (hostname: monitor, domain: megacorp.ex)"
echo ""
read Domain
if [ -z "$Domain" ]
then
	Domain="local"
fi
DNSName=$Hostname.$Domain
echo "Please enter a POSIX TimeZone (default: Atlantic/Reykjavik)"
echo "$ find /usr/share/zoneinfo/posix/ | sed 's/\/usr\/share\/zoneinfo\/posix\///'"
echo "will give you a list"
read TZ
if [ -z "$TZ" ]
then
	TZ="Atlantic/Reykjavik"
fi
if [ ! -f "/usr/share/zoneinfo/posix/$TZ" ]
then
	echo "Invalid TimeZone $TZ, setting to default"
	TZ="Atlantic/Reykjavik"
fi

APIKey=`tr -cd '[:alnum:]' < /dev/urandom | fold -w32 | head -n1`
SQLPass=`tr -cd '[:alnum:]' < /dev/urandom | fold -w16 | head -n1`


if [ -f "/etc/sensa/librenms/pbvars.yaml" ]
then
    sudo rm /etc/sensa/librenms/pbvars.yaml
fi

PWD=`pwd`

echo "# File generated by kickstart script

HOST: $Hostname
DOMAIN: $Domain
URL: $DNSName

MYSQL_DATABASE: librenms
MYSQL_USER: librenms
MYSQL_PASSWORD: $SQLPass

SMTP_SERVER: "smtp.example.corp"
SMTP_USERNAME: "librenms@example.corp"
SMTP_PASSWORD: "supersecuresmtppassword"

CPE_USERNAME: $CPEUser
CPE_PASSWORD: $CPEPass
API_TOKEN: $APIKey
BASE_DIR: $BaseDIR

TZ: $TZ
PUID: 1000
PGID: 1000" > pbvars.yaml

if [ "$PWD" = "/etc/sensa/librenms" ]
then
    exit 0
fi

if [ -f "/etc/sensa/librenms" ]
then
    sudo cp pbvars.yaml /etc/sensa/librenms/pbvars.yaml
fi